### PR TITLE
Hydra

### PR DESCRIPTION
**Pull request by svelardita**
90% of the files have been changed because I've formatted everything with the CLANG format. The main modifications in the code that I introduced are in the folder: gtpc and macros.
In /gptc the files that I modified are: R3BGTPC.*, R3BGTPCSetup*.
In /macros/geo: create_HYDRA*.
In /macros/proj: run*.
In /macros/sim: almost everything.
In /macros/vis: run*.
In all the macros I added the possibility to switch between the different HYDRA geometries using a TSTRING GEOTAG. I hope this is the best option, but we can discuss it.

### CODE REVIEW

**Review by hapol — CHANGES_REQUESTED** [review]
Could you please move the PrimaryGenerators folder one step up? It should be either in the general R3BRoot/r3bgen folder or, if you wish to have them as separated generators only for HYDRA, in a new directory in the HYDRA section called gtpcgen (for the moment...).

**Review by hapol — COMMENTED** [review]
Why there should be folders in the macro section for each geometry? They contains the same macros duplicated. Is the analysis related to the particular detector in any sense? In principle the analysis macros could be identical for all, just taken into account that the number or pads or geometrical correspondence is different for each model...

**Comment by svelardita** [comment]
> Could you please move the PrimaryGenerators folder one step up? It should be either in the general R3BRoot/r3bgen folder or, if you wish to have them as separated generators only for HYDRA, in a new directory in the HYDRA section called gtpcgen (for the moment...).

I created the new folder gtpcgen and made in the generator few aesthetics adjustments.

**Comment by svelardita** [comment]
> Why there should be folders in the macro section for each geometry? They contains the same macros duplicated. Is the analysis related to the particular detector in any sense? In principle the analysis macros could be identical for all, just taken into account that the number or pads or geometrical correspondence is different for each model...

The three folders are mainly used to store the output file (par.root and sim.root) for the three different detectors. In this way, I can easily work with them without confusion and compare the results. The last point is crucial for the two versions of the full-size detector.

**Pull request merged**
